name: Weblate export
run-name: ${{ github.actor }} is run export to Weblate

on: 
  workflow_dispatch:
    inputs:
      previousBranch:
        description: Please enter the previous weblate output branch name
  
jobs:
  commit-weblate-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Commit Weblate branches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://${{ secrets.WEBLATE_URL }}/api/projects/angular-test/repository/'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.WEBLATE_TOKEN }}"}'
        data: '{"operation": "commit"}'
        
  push-weblate-changes:
    needs: commit-weblate-changes
    runs-on: ubuntu-latest
    
    steps:
    - name: Commit Weblate branches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://${{ secrets.WEBLATE_URL }}/api/projects/angular-test/repository/'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.WEBLATE_TOKEN }}"}'
        data: '{"operation": "push"}'
        
  create-pull-request:
    needs: push-weblate-changes
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.previousBranch }}
        
    - run: git fetch origin
        
    - run: git config --global merge.ours.driver true
    
    - run: git merge origin/master
        
    - name: create pull request
      run: gh pr create -B master --title 'Localization Merge ${{ github.event.inputs.previousBranch }} into master' --body 'Localization Pull Request Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
  create-new-branch:
    needs: create-pull-request
    runs-on: ubuntu-latest
    
    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: wirthandras
        issue-title: "Wait for Localization Merge to master from output branch"
   
    - uses: actions/checkout@v3
    
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ github.run_number }}-input'
        sha: '${{ github.event.pull_request.head.sha }}'        
        
    - uses: actions/checkout@v3
      with:
        ref: 'weblate-export-${{ github.run_number }}-input'
        
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - run: npm ci
    
    - run: npm run extract-i18n
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        
  create-output-branch:
    needs: create-new-branch
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: weblate-export-${{ github.run_number }}-input
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ github.run_number }}-output'
            
  update-weblate-branches:
    needs: create-output-branch
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Weblate branches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://${{ secrets.WEBLATE_URL }}/api/components/angular-test/angular/'
        method: 'PATCH'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.WEBLATE_TOKEN }}"}'
        data: '{"branch": "weblate-export-${{ github.run_number }}-input", "push_branch": "weblate-export-${{ github.run_number }}-output"}'
