name: Weblate export
run-name: ${{ github.actor }} is run export to Weblate

on: 
  workflow_dispatch:
  
jobs:
 
  weblate-export:
    runs-on: ubuntu-latest
    steps:
   
    - uses: actions/checkout@master
    
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ env.GITHUB_RUN_NUMBER }}-input'
        sha: '${{ github.event.pull_request.head.sha }}'        
        
    - uses: actions/checkout@v3
      with:
        ref: 'weblate-export-${{ env.GITHUB_RUN_NUMBER }}-input'
        
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - run: npm ci
    
    - run: npm run extract-i18n
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        
  create-output-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@weblate-export-${{ env.GITHUB_RUN_NUMBER }}-input
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ env.GITHUB_RUN_NUMBER }}-output'  
