name: Weblate export
run-name: ${{ github.actor }} is run export to Weblate

on: 
  workflow_dispatch:
jobs:
 
  weblate-export:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"   
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ steps.date.outputs.date }}'
        sha: '${{ github.event.pull_request.head.sha }}'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm extract-i18n
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
