name: Weblate export
run-name: ${{ github.actor }} is run export to Weblate

on: 
  workflow_dispatch:
  
jobs:
  commit-weblate-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Commit Weblate branches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://${{ secrets.WEBLATE_URL }}/api/projects/angular-test/repository/'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.WEBLATE_TOKEN }}"}'
        data: '{"operation": "commit"}'
        
  push-weblate-changes:
    needs: commit-weblate-changes
    runs-on: ubuntu-latest
    
    steps:
    - name: Commit Weblate branches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://${{ secrets.WEBLATE_URL }}/api/projects/angular-test/repository/'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.WEBLATE_TOKEN }}"}'
        data: '{"operation": "push"}'
 
  create-new-branch:
    needs: push-weblate-changes
    runs-on: ubuntu-latest
    steps:
   
    - uses: actions/checkout@v3
    
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ github.run_number }}-input'
        sha: '${{ github.event.pull_request.head.sha }}'        
        
    - uses: actions/checkout@v3
      with:
        ref: 'weblate-export-${{ github.run_number }}-input'
        
    - uses: actions/setup-node@v3
      with:
        node-version: 12
    - run: npm ci
    
    - run: npm run extract-i18n
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        
  create-output-branch:
    needs: create-new-branch
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: weblate-export-${{ github.run_number }}-input
    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'weblate-export-${{ github.run_number }}-output'
            
  update-weblate-branches:
    needs: create-output-branch
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Weblate branches
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://${{ secrets.WEBLATE_URL }}/api/components/angular-test/angular/'
        method: 'PATCH'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.WEBLATE_TOKEN }}"}'
        data: '{"branch": "weblate-export-${{ github.run_number }}-input", "push_branch": "weblate-export-${{ github.run_number }}-output"}'
