on: 
  workflow_dispatch:
    uses: peterjgrainger/action-create-branch@v2.2.0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      branch: 'weblate-export-${{ steps.date.outputs.date }}'
      sha: '${{ github.event.pull_request.head.sha }}'
